package bus.ticket.reservation.system;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package bus.ticket.reservation.system.signup;

import bus.ticket.reservation.system.loginform;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;

import com.sun.glass.events.KeyEvent;
import java.awt.Component;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;



 
//import com.itextpdf.text.pdf.PdfWriter;
 

/**
 *
 * @author Zarar bhai
 */
public class ticketreservation extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    DefaultTableModel model=new DefaultTableModel();
     String page1;
     String Name;
        String CNIC;
        String adress;
        String phone;
        String seats;
        String to;
        String from;
        String category;
        String t;
        String d;
        String price;
    /**
     * Creates new form ticketreservation
     */
    public ticketreservation() {
        initComponents();
        conn=ticketreservation.connectdb();
        
        Calendar cal = new GregorianCalendar();
    int month =cal.get(Calendar.MONTH);
    int year =cal.get(Calendar.YEAR);
    int day =cal.get(Calendar.DAY_OF_MONTH);
    cmb_date.addItem(+year+"-"+(month+1)+"-"+day);
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+1));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+2));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+3));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+4));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+5));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+6));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+7));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+8));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+9));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+10));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+11));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+12));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+13));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+14));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+15));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+16));
    cmb_date.addItem(+year+"-"+(month+1)+"-"+(day+17));
    
    
    }
    public static Connection connectdb(){
        try{
            Class.forName("org.sqlite.JDBC");
            Connection conn=DriverManager.getConnection("jdbc:sqlite:C:\\sqlite\\bussystem.db");
            System.out.println("connected");
            return conn;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cnictxt = new javax.swing.JTextField();
        phonetxt = new javax.swing.JTextField();
        adresstxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        seatstxt = new javax.swing.JTextField();
        categorytxt = new javax.swing.JComboBox<>();
        cmb_date = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtto = new javax.swing.JComboBox<>();
        timingtxt = new javax.swing.JComboBox<>();
        txtfrom = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpane = new javax.swing.JEditorPane();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 12), "Your Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 51))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("RESERVE YOUR TICKET");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Full Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Adress:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Phone No:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("CNIC:");

        cnictxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cnictxt.setForeground(new java.awt.Color(0, 102, 102));

        phonetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phonetxt.setForeground(new java.awt.Color(0, 102, 102));
        phonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonetxtActionPerformed(evt);
            }
        });

        adresstxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adresstxt.setForeground(new java.awt.Color(0, 102, 102));

        nametxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nametxt.setForeground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("No. of Seats:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("To:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("From:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Class:");

        seatstxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seatstxt.setForeground(new java.awt.Color(0, 102, 102));
        seatstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatstxtActionPerformed(evt);
            }
        });
        seatstxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                seatstxtKeyTyped(evt);
            }
        });

        categorytxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        categorytxt.setForeground(new java.awt.Color(0, 102, 102));
        categorytxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        cmb_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_date.setForeground(new java.awt.Color(0, 102, 102));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Date:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Timing:");

        txtto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtto.setForeground(new java.awt.Color(0, 102, 102));
        txtto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rawalpindi", "Multan", "Kashmir", "Karachi", "Lahore", "Quetta" }));

        timingtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timingtxt.setForeground(new java.awt.Color(0, 51, 51));
        timingtxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:30 Morning", "12:00 Noon", "3:00 AfterNoon", "6:00 Evening", "9:00 Night" }));
        timingtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timingtxtActionPerformed(evt);
            }
        });

        txtfrom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtfrom.setForeground(new java.awt.Color(0, 102, 102));
        txtfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rawalpindi", "Multan", "Kashmir", "Karachi", "Lahore", "Quetta" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_date, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cnictxt, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))))
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfrom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seatstxt, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(timingtxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categorytxt, 0, 240, Short.MAX_VALUE))))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtto, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfrom, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(categorytxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cnictxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timingtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 12), "Ticket", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 51))); // NOI18N

        txtpane.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtpane.setForeground(new java.awt.Color(0, 102, 102));
        jScrollPane2.setViewportView(txtpane);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("PRINT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 102));
        jButton6.setText("SAVE TICKET");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                .addGap(72, 72, 72))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonetxtActionPerformed

    private void seatstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatstxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Name=nametxt.getText();
        CNIC=cnictxt.getText();
        adress=adresstxt.getText();
        phone=phonetxt.getText();
        seats=seatstxt.getText();
        to=txtto.getSelectedItem().toString();
        from=txtfrom.getSelectedItem().toString();
        category=categorytxt.getSelectedItem().toString();
        t=timingtxt.getSelectedItem().toString();
        d=cmb_date.getSelectedItem().toString();
        
        
        if(category.equals('A')){
            price="5000";
        }else if(category.equals('B')){
            price="3000";
        }else if(category.equals('C')){
            price="2000";
    }else{
            price="1000";
            }
        int p=Integer.parseInt(price)*Integer.parseInt(seats);
        price=Integer.toString(p);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");  
        LocalDateTime now = LocalDateTime.now();  
        System.out.println(dtf.format(now));
        int minimum=3;
        int maximum=1000;
        double num=minimum + (int)(Math.random() * maximum);
        boolean a=check(to,from);
        String bus_no="ABC"+Double.toString(num);
        page1="                                           Ticket Reservation System                          \n"
            + "                                                                                       "+now+"\n"
            +"       Date:    "+d+"                          "+"                                     Timing: "+t+"\n"
            + "      Name:    "+Name+"                       "+"                                     To:     "+to+"\n"
            + "      Phone:   "+phone+"                     "+"                                           From:   "+from+"\n"
            + "      Adress:  "+adress+"                   "+"                                                      Seats:  "+seats+"\n"
            + "      CNIC:    "+CNIC+"                       "+"                                               Class:  "+category+"\n"
            + "      Price:   "+price+"                     "+"                                               Status: Unpaid\n"
            +"                                                                                       Bus. No: "+bus_no+"";
        if(a){
            boolean c=checktime(t,to,from);
            if(c){
                boolean s=checkseats(seats);
                if(s){
                   try{
                    txtpane.setText(page1);
                   }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e+"abc");
                }
                String sql="INSERT INTO ticketreservation(Name,Adress,phoneno,CNIC,Date,seats,destination,Start,Class,Timing)"
                + "VALUES(?,?,?,?,?,?,?,?,?,?)";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, Name);
            pst.setString(2, adress);
            pst.setString(3, phone);
            pst.setString(4, CNIC);
            pst.setString(5, d);
            pst.setString(6, seats);
            pst.setString(7, to);
            pst.setString(8, from);
            pst.setString(9, category);
            pst.setString(10, t);
            
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data Inserted Successfully");
            adminclass ad=new adminclass();
            String[] args = null;
            
            adminclass.setdata();
            pst.close();
            updateseats();
            
            //rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex+"System not Updated Successfully");
            System.out.println(ex);
        }
                }else{
                    JOptionPane.showMessageDialog(null,"Sorry! Seats are not available");
                }
                
            }else{
                JOptionPane.showMessageDialog(null,"Sorry! No bus available at this time");
            }
        
        }else{
            JOptionPane.showMessageDialog(null,"Sorry! No bus available!");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    JFrame frame=new JFrame();
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        MessageFormat header=new MessageFormat("Printing in Progress!");
        MessageFormat footer=new MessageFormat("page 0");
        try{//
            txtpane.print(header,footer);
           
        } catch (PrinterException ex) {
            Logger.getLogger(ticketreservation.class.getName()).log(Level.SEVERE, null, ex);
          
            
               
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void seatstxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seatstxtKeyTyped
        // TODO add your handling code here:
        char iNum=evt.getKeyChar();
        if(!(Character.isDigit(iNum))||(iNum==KeyEvent.VK_BACKSPACE)||(iNum==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_seatstxtKeyTyped
    private JFrame frame1;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        frame=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit!", "Bus Reservation System", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JTextField temp=null;
        for(Component c:jPanel1.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                temp=(JTextField)c;
                temp.setText(null);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loginform lg=new loginform();
        this.setVisible(false);
        lg.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
            String filename=""+Name+"_ticket.png";
            saveScreenShot(jPanel2,filename);
            JOptionPane.showMessageDialog(null,"Ticket Saved!");
        } catch (Exception ex) {
            Logger.getLogger(ticketreservation.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Don't Saved!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void timingtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timingtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timingtxtActionPerformed
    private static BufferedImage getScreenShot(Component com){
        BufferedImage image=new BufferedImage(com.getWidth(),com.getHeight(),BufferedImage.TYPE_INT_RGB);
        
        com.paint(image.getGraphics());
        return image;
    }
    private static void saveScreenShot(Component com,String filename)throws Exception{
        BufferedImage img=getScreenShot(com);
        
        ImageIO.write(img,"png", new File(filename));
        
    }
    private boolean check(String to,String from){
        boolean response=false;
        conn=ticketreservation.connectdb();
        String sql="select destination,Start from Buses";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            System.out.println(" "+to+" "+from);
            while(rs.next()){
                System.out.println(" "+rs.getString("destination")+" "+rs.getString("Start"));
                if(rs.getString("destination").equals(to) && rs.getString("Start").equals(from)){
                    
                    response=true;
                    break;
                }
            }
            pst.close();
            
            rs.close();
        
        }catch(Exception e){
            
        }
        
        return response;
    }
    public boolean checktime(String time,String t,String f){
        boolean response=false;
        conn=ticketreservation.connectdb();
        String sql="select destination,Start, Timing from Buses";
        System.out.println("AAAA");
        try{
            pst=conn.prepareStatement(sql);
            System.out.println("BBBB");
            rs=pst.executeQuery();
            while(rs.next()){
                System.out.println(rs.getString("Timing"));
                System.out.println(time);
                if(rs.getString("Start").equals(f) && rs.getString("destination").equals(t)){
                    if(rs.getString("Timing").equals(time)){
                    response=true;
                    
                    break;
                }
                }
                
            }
            pst.close();
            
                    rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        return response;
    }
    public boolean checkseats(String seats){
        boolean response=false;
        conn=ticketreservation.connectdb();
        String sql="select destination,Start,Seats from Buses";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                if(rs.getString("destination").equals(to) && rs.getString("Start").equals(from)){
                    if(Integer.parseInt(rs.getString("Seats"))>0 && Integer.parseInt(rs.getString("Seats"))>Integer.parseInt(seats) ){
                        //System.out.print(Integer.parseInt(rs.getString("Seats"));
                        System.out.println(rs.getString("Seats")+"end");
                        response=true;
                        break;
                    }
                }
            }
            pst.close();
            
                    rs.close();
        }catch(Exception e){
            
        }
        return response;
    }
    public void updateseats(){
        
        //Connection conn=ticketreservation.connectdb();
        String seat=seatsremaining();
        String bn=busnumber();
        System.out.println(bn);
        System.out.println(seat);
        int s=Integer.parseInt(seat);
        //String sql1="select destination,busno, Start from Buses";
        String sql="update Buses set "
                + "Seats=? "
                + "where busno=?";
            
            try{
               pst=conn.prepareStatement(sql);
               pst.setString(1, seat);
               pst.setString(2, bn);
               pst.execute();
               
               //JOptionPane.showMessageDialog(null, "Seats updated successfully");
               pst.close();
            
                    
               
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                System.out.println(e);
            }
            
    }
    public String seatsremaining(){
        String s=null;
        String sql="select destination,Start, Seats from Buses";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
              if(rs.getString("Start").equals(from)&& rs.getString("destination").equals(to)){
                    int a=Integer.parseInt(rs.getString("Seats"))-Integer.parseInt(seats);
                    s=Integer.toString(a);
                    System.out.println(a);
                    pst.close();
            
                    rs.close();
                    break;
                    
                }  
            }
            pst.close();
            
                    rs.close();
        }catch(Exception e){
            
        }
        return s;
    }
    public String busnumber(){
        String bn=null;
        String sql="select busno,destination,Start from Buses";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
              if(rs.getString("Start").equals(from)&& rs.getString("destination").equals(to)){
                    bn=rs.getString("busno");
                    System.out.println(bn);
                    pst.close();
            
                    rs.close(); 
                    break;
                    
                }  
            }
           pst.close();
            
                    rs.close(); 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
             
        }
        return bn;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticketreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticketreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticketreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticketreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticketreservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresstxt;
    private javax.swing.JComboBox<String> categorytxt;
    private javax.swing.JComboBox<String> cmb_date;
    private javax.swing.JTextField cnictxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JTextField seatstxt;
    private javax.swing.JComboBox<String> timingtxt;
    private javax.swing.JComboBox<String> txtfrom;
    private javax.swing.JEditorPane txtpane;
    private javax.swing.JComboBox<String> txtto;
    // End of variables declaration//GEN-END:variables
}
